vianetwork/via-core

core/lib/via_btc_client/DEV.md, core/lib/via_btc_client/src/indexer/mod.rs, core/lib/via_btc_client/src/indexer/parser.rs, core/lib/via_btc_client/src/inscriber/script_builder.rs, core/lib/via_btc_client/src/types.rs
This PR updates the Bootstraping inscription and introduce the `bootloader_hash` and  the `account_abstraction_hash`. 
The `bootloader_hash` and the `account_abstraction_hash` are used to compute the L1 batch and will be used to fetch the L1 block to create inscription requests.
=> feat(btc_client): Add bootloader hash and AA hash to the bootstraping inscription

etc/env/configs/via.toml
- Update the vial.toml file to import the `via.init.env` instead of the `dev.init.env`.
If you don't have `via.init.env`, make sure to run the cmd `via config compile` before `via init`
=> fix: import via init env instead of the dev

core/bin/via_server/src/main.rs, core/bin/via_server/src/node_builder.rs
This PR will enable the http-api RPC server which requires sub layers like:
- The `TreeApiClientLayer` which is required to fetch the Batch proofs.
- The `MempoolCacheLayer` is a layer used to cache the l2 transactions received by the mempool.
This PR depends on the PR #25 
The RPC server is used to send and query data from the sequencer.
- Use the `via server` to run the server.
- Seed a dummy block to the database.
- query using
```sh
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "zks_L1ChainId", "params": [], "id": 1}' http://localhost:3050
```
=> feat(http-api): add http api layer

core/node/node_framework/src/implementations/layers/via_btc_sender/aggregator.rs, core/node/node_framework/src/implementations/layers/via_btc_sender/manager.rs
- Add auth credentials to connect to the btc rpc node.
- When the btc_sender calls the btc node it gets HTTP401 due to missing credentials.
- Insert a dummy l1 batch with other data dependencies [here](https://github.com/vianetwork/via-core/blob/90018208e3749f8dc1b01a06eef64e9f60188a51/core/node/via_btc_sender/src/tests/utils.rs#L170)
- Run `via server`
The reveal and commit tx ids are inserted.
The inscription history is recorded.
=> fix(btc_sender): add auth credentials to connect to the rpc node

core/bin/via_server/src/main.rs, core/bin/via_server/src/node_builder.rs
**Fixing the Issue with Code Panic During the First `via server` Execution**
**Approach:**
I’m adopting a similar approach to what zkSync uses. When running the server for the first time, there are two steps 
required:
1. `via server --genesis`
2. `via server`
However, if the **genesis block already exists in the database**, you only need to run:
• `via server`
=> Fix/ Code Panic During the genesis phase

core/node/via_fee_model/src/lib.rs
Remove scaling the L1 gas price to X100 compared to l2 gas price, because it blocks the L2 sealer task to create new miniblocks.
=> Fix/via fee model: remove scaling the L1 gas price

core/node/via_btc_watch/src/lib.rs, core/node/via_btc_watch/src/message_processors/l1_to_l2.rs, core/node/via_btc_watch/src/message_processors/mod.rs, core/node/via_btc_watch/src/metrics.rs
This PR provides new `via_server_btc_watch` metrics. The list of all edited metrics (prefixes) is:
| zksync    | via |
| -------- | ------- |
| server_da_dispatcher | via_server_da_dispatcher |
| server_state_keeper |  via_server_state_keeper |
| server_tx_aggregation | via_server_tx_aggregation |
| server_state_keeper_l1_batch | via_server_state_keeper_l1_batch |
| server_state_keeper_miniblock | via_server_state_keeper_miniblock |
| batch_tip | via_batch_tip |
| server_state_keeper_updates_manager | via_server_state_keeper_updates_manager |
| server_eth_watch | via_server_btc_watch |
=> feat: metrics

core/node/api_server/src/tx_sender/mod.rs
- set the correct version of the Bootloader contract (playground) for `eth_call` requests.
- This Bootloader version should provide better UX with revert messages.
=> fix: use correct bootloader version for eth_call

core/node/via_btc_sender/src/btc_inscription_aggregator.rs
- Update the bootleader and AA hashes in the btc_sender
=> fix: set the last bootloarder and aa hashes

docker/prover-cli/Dockerfile
- Add Dockerfile for `prover-cli`.
- So we can perform prover command (db setup for protocol version etc.) from the container or similar environments (pods).
=> build: add Dockerfile for `prover-cli`

.dockerignore, docker/server/Dockerfile
Update `server` Dockerfile to work with devnet-2 version.
=> Dockerize server for devnet-2

core/node/via_btc_sender/src/aggregator.rs, core/node/via_btc_sender/src/btc_inscription_manager.rs, infrastructure/via/src/env.ts
This PR fixes problem with `env` during server restart.
Try after stopping server:
```bash
/* via cli re-compile here */
via env via --soft
via server
```
`--soft` will not re-compile configs.
=> fix: server restart, update via cli, minor logs changes

infrastructure/via/src/config.ts, infrastructure/via/src/index.ts, infrastructure/via/src/test/test.ts
- `via test rust` command added to via cli for running unit tests with `cargo-nextest`
- Enables all Via tests (from all crates prefixed with `via_`) to be run with `via test rust -p 'via_*'`, even the ones from Via node components that need access to test db
=> feat: Add via command for running unit tests

core/node/via_btc_sender/src/btc_inscription_aggregator.rs, core/node/via_btc_sender/src/btc_inscription_manager.rs, core/node/via_btc_watch/src/lib.rs, via_verifier/lib/verifier_dal/src/via_btc_sender_dal.rs, via_verifier/lib/via_da_client/src/pubdata.rs, via_verifier/lib/via_da_client/src/types.rs, via_verifier/lib/via_musig2/src/transaction_builder.rs, via_verifier/lib/via_withdrawal_client/src/withdraw.rs, via_verifier/node/via_btc_sender/src/btc_inscription_manager.rs, via_verifier/node/via_btc_sender/src/btc_vote_inscription.rs, via_verifier/node/via_btc_watch/src/lib.rs, via_verifier/node/via_verifier_coordinator/src/auth.rs, via_verifier/node/via_verifier_coordinator/src/coordinator/api.rs, via_verifier/node/via_verifier_coordinator/src/coordinator/api_decl.rs, via_verifier/node/via_verifier_coordinator/src/sessions/withdrawal.rs, via_verifier/node/via_verifier_coordinator/src/utils.rs, via_verifier/node/via_verifier_coordinator/src/verifier/mod.rs, via_verifier/node/via_zk_verifier/src/lib.rs
- Improve the error handling by using `with_context` instead of `context` to avoid override the original error. 
- Remove not required `.context(...)`
When use `context` the original error is override and it becomes hard to debug
=> fix: replace context with with_context and remove not required context

core/lib/via_btc_client/examples/data_inscription_example.rs, core/lib/via_btc_client/src/inscriber/mod.rs, rust-toolchain
Resolve Dust Limit in inscription transaction for mainnet
`const P2TR_DUST_LIMIT: Amount = Amount::from_sat(330);`
**Reference:** 
https://bitcointalk.org/index.php?topic=5453107.msg62262343#msg62262343
https://bitcoin.stackexchange.com/questions/10986/what-is-meant-by-bitcoin-dust
**commit tx** 
**reveal tx**
=> Resolve Dust Limit in inscription tx for mainnet

core/lib/via_btc_client/DEV.md, core/lib/via_btc_client/examples/bootstrap.rs, core/lib/via_btc_client/src/indexer/mod.rs, core/lib/via_btc_client/src/indexer/parser.rs, core/lib/via_btc_client/src/inscriber/script_builder.rs, core/lib/via_btc_client/src/types.rs
Add governance address to the bootstrap inscription.
The governance wallet is used to create upgradable transactions.
=> feat: add governance address to the bootstrap inscription

docker-compose-via-btc-explorer.yml, docker-compose-via.yml, infrastructure/via/src/clean.ts
- Remove the local `db` folder used by state keeper when cleaning the setup in order to avoid invalid L1 batches when running the setup next time.
- Remove version warnings in docker compose files.
=> fix: remove db folder when cleaning the setup

Cargo.lock, core/bin/via_server/src/node_builder.rs, core/lib/via_btc_client/examples/deposit.rs, core/lib/via_btc_client/examples/deposit_opreturn.rs, core/node/node_framework/src/implementations/layers/via_btc_watch.rs, core/node/via_btc_watch/Cargo.toml, core/node/via_btc_watch/src/lib.rs, core/node/via_btc_watch/src/message_processors/l1_to_l2.rs, infrastructure/via/src/token.ts
- Add fee estimation to `deposit` and `deposit-with-op-return`.
- Reduce the `gas_limit` when create an L1Tx in the btc_watcher
- Use the BaseBatchFee model in `btc_watch` and use the l2_faire_gas_price to  the gas price
The PR was opened to improve gas efficiency and accuracy by replacing hardcoded gas fees and prices with dynamic estimates from the ZKS API, and to lower the excessively high `gas_limit` to reduce unnecessary refunds.
- The first transaction is `deposit`.
1. Use via CLI to `deposit` and `deposit-with-op-return`
2. The transaction should be processed by the sequencer.
3. Check the transaction
```sql
select 
full_fee,
layer_2_tip_fee,
gas_limit,
gas_per_storage_limit,
gas_per_pubdata_limit,
max_fee_per_gas,
max_priority_fee_per_gas,
effective_gas_price,
refunded_gas
from …
```
=> refactor: estimate the deposit fee cost

via_verifier/lib/via_musig2/src/lib.rs
- Improve MuSig2 nonce generation (first round) security.
- It is recommended to use cryptographically secured OS level random number generator for generating nonce seed (`OsRng`), so that there is no possibility of reusing the same seed in multiple signing sessions.
=> fix: improve musig2 nonce seed generation

core/lib/config/src/configs/via_btc_watch.rs, core/lib/dal/.sqlx/query-12c639fe438fe1346d155e0e4c1f9b30cd2a4db38a78070bf49c688300dc6a57.json, core/lib/dal/.sqlx/query-89f90028bc6cf29d115c19300f222c2810c93f0a710f9f22e4af9d5772c4cb8c.json, core/lib/dal/.sqlx/query-fd1ad398bb74265ad5ce31de56c8f987d9775717f9117030dc2dd369c29a5291.json, core/lib/dal/migrations/20250414100204_via_indexer_metadata.down.sql, core/lib/dal/migrations/20250414100204_via_indexer_metadata.up.sql, core/lib/dal/src/lib.rs, core/lib/dal/src/via_indexer_dal.rs, core/node/node_framework/src/implementations/layers/via_btc_watch.rs, core/node/node_framework/src/implementations/layers/via_verifier_btc_watch.rs, core/node/via_btc_watch/src/lib.rs, etc/env/configs/via_base.toml, etc/env/configs/via_coordinator.toml, etc/env/configs/via_verifier.toml, via_verifier/lib/verifier_dal/.sqlx/query-12c639fe438fe1346d155e0e4c1f9b30cd2a4db38a78070bf49c688300dc6a57.json, via_verifier/lib/verifier_dal/.sqlx/query-89f90028bc6cf29d115c19300f222c2810c93f0a710f9f22e4af9d5772c4cb8c.json, via_verifier/lib/verifier_dal/.sqlx/query-fd1ad398bb74265ad5ce31de56c8f987d9775717f9117030dc2dd369c29a5291.json, via_verifier/lib/verifier_dal/migrations/20250414100204_via_indexer_metadata.down.sql, via_verifier/lib/verifier_dal/migrations/20250414100204_via_indexer_metadata.up.sql, via_verifier/lib/verifier_dal/src/lib.rs, via_verifier/lib/verifier_dal/src/via_indexer_dal.rs, via_verifier/node/via_btc_watch/src/lib.rs
- Fix the logic where the indexer start indexing the L1 blocks (Sequencer and verifier).
- Adding pagination logic to the L1 blocks selection to avoid memory issues due to selecting many blocks at a time.
- Added a new table `via_indexer_metadata` to track the last indexed L1 block number.
- Added logic to allow restart indexing the L1 chain from a specific L1 block number. This logic can in create duplicates transactions as it's handled by the message processor.
- At some point we will need to restart the indexer at a specific L1 block number.
- Avoid loading a lots of L1 blocks in memory during the message processing checks.
1. Start the sequencer.
2. Deposit BTC.
3. You should see this in DB
4. Stop the sequencer and update the `via.env` and update the …
=> fix: btc_watch logic index l1 starting block

core/lib/config/src/configs/via_btc_client.rs, core/lib/config/src/configs/via_btc_sender.rs, core/lib/config/src/configs/via_verifier.rs, core/lib/config/src/configs/via_wallets.rs, core/lib/env_config/src/via_wallets.rs, core/node/node_framework/src/implementations/layers/via_btc_sender/aggregator.rs, core/node/node_framework/src/implementations/layers/via_btc_sender/manager.rs, core/node/node_framework/src/implementations/layers/via_btc_sender/vote_manager.rs, core/node/node_framework/src/implementations/layers/via_verifier/coordinator_api.rs, core/node/node_framework/src/implementations/layers/via_verifier/verifier.rs, etc/env/base/via_private.toml, etc/env/configs/via_coordinator.toml, etc/env/configs/via_verifier.toml
- Add the wallet endpoint to the bitcoin RPC url. 
To track and list he utxos, the wallet needs to be added to the node, this will index the utxos. And to list those utxos on  `Testnet` and `Bitcoin` networks we have to set the wallet endpoint `http://127.0.0.1:8332/wallet/testwallet`,
Without this fix, the node will returns empty list of utxos.
=> Fix: add wallet endpoint to the btc rpc url

core/lib/via_btc_client/src/client/fee_limits.rs, core/lib/via_btc_client/src/client/mod.rs
- Add fee rate limits (min, max) for Bitcoin transactions.
- To prevent high gas fee for inscriptions and avoid fee rate spike issues (mainly occurring on Testnet).
=> Add fee rate limits

Cargo.lock, core/lib/via_btc_client/Cargo.toml, core/lib/via_btc_client/src/client/mod.rs, core/lib/via_btc_client/src/inscriber/mod.rs, core/lib/via_btc_client/src/inscriber/script_builder.rs, core/lib/via_btc_client/src/lib.rs, core/lib/via_btc_client/src/metrics.rs, core/lib/via_btc_client/src/utils.rs, core/node/via_btc_sender/src/btc_inscription_manager.rs, via_verifier/lib/via_musig2/src/lib.rs, via_verifier/lib/via_musig2/src/utils.rs, via_verifier/node/via_btc_sender/src/btc_inscription_manager.rs, via_verifier/node/via_verifier_coordinator/src/coordinator/api_impl.rs, via_verifier/node/via_verifier_coordinator/src/metrics.rs, via_verifier/node/via_verifier_coordinator/src/verifier/mod.rs
- Verify the partial signature if valid.
- Added unit test to verify the partial signature.
- Integrate the logic into the withdrawal session.
When a new session is initialized, some verifiers may still use stale session data. This can result in invalid partial signatures being submitted to the coordinator. If such signatures are accepted, they can corrupt the session state and require a manual restart of the coordinator to clean up memory.
This PR addresses the issue by introducing validation of partial signatures. If a submitted signature is found to be invalid, the session is reset. This mechanism ensures that verifiers are forced to clear their local state and fetch the latest valid session data from the coordinator.
=> feat: add verify partial signature

docker-compose-via-btc-explorer.yml, docker-compose-via.yml, infrastructure/via/src/celestia.ts, infrastructure/via/src/transactions.ts
- Bumps the Celestia light node version to `v0.23.0`.
- Removes the fixed prefix (`via-core`) in container names used to reference containers for command execution. Instead, a more flexible approach using the `docker compose exec` command is implemented.
- The newest stable version of Celestia has effectively deprecated older versions.
- The hardcoded prefixes in container names restricted the setup script to only work within a `via-core` folder (typically created by the `git clone` command). When specifying a different folder name (e.g., `git clone <url> via-local`), the setup script would fail as it couldn't locate containers with the expected names.
=> chore: bump um celestia and improve docker local setup

core/lib/via_btc_client/src/indexer/mod.rs, core/lib/via_btc_client/src/indexer/parser.rs, via_verifier/lib/verifier_dal/.sqlx/query-91c394e34bb6a1595233ad927cc85ab341dd742c177c2b16c7a88749726b8854.json, via_verifier/lib/verifier_dal/.sqlx/query-b5ca9a8c4de88ba04dcc3ff43d2402c8f34128f88006928567d026fb78e08cbf.json, via_verifier/lib/verifier_dal/src/via_votes_dal.rs, via_verifier/node/via_btc_watch/src/lib.rs, via_verifier/node/via_btc_watch/src/message_processors/mod.rs, via_verifier/node/via_btc_watch/src/message_processors/withdrawal.rs, via_verifier/node/via_btc_watch/src/metrics.rs, via_verifier/node/via_verifier_coordinator/src/sessions/withdrawal.rs, via_verifier/node/via_verifier_coordinator/src/traits.rs, via_verifier/node/via_verifier_coordinator/src/verifier/mod.rs
- Add validation logic  to check if the expected bridge address created the inscription.
- This PR allows to ignore inscriptions that where not created by the authorized bridge address.
- This PR is a parent of the #206 , follow the PR description for more details about testing process.
=> feat: validate the bridge withdrawal inscription

Makefile, core/lib/config/src/configs/via_verifier.rs, core/lib/types/src/via_protocol_upgrade.rs, core/lib/via_btc_client/Cargo.toml, core/lib/via_btc_client/examples/upgrade_inscription_parsing.rs, core/lib/via_btc_client/examples/upgrade_system_contracts.rs, core/lib/via_btc_client/src/indexer/mod.rs, core/lib/via_btc_client/src/indexer/parser.rs, core/lib/via_btc_client/src/inscriber/script_builder.rs, core/lib/via_btc_client/src/types.rs, core/node/node_framework/src/implementations/layers/via_btc_watch.rs, core/node/node_framework/src/implementations/layers/via_verifier_btc_watch.rs, core/node/via_btc_watch/src/lib.rs, core/node/via_btc_watch/src/message_processors/governance_upgrade.rs, core/node/via_btc_watch/src/message_processors/votable.rs, docker-compose-via.yml, docs/via_guides/upgrade.md, infrastructure/via/package.json, infrastructure/via/src/helpers.ts, infrastructure/via/src/index.ts, infrastructure/via/src/multisig.ts, via_verifier/node/via_btc_watch/src/lib.rs, via_verifier/node/via_btc_watch/src/message_processors/governance_upgrade.rs, via_verifier/node/via_btc_watch/src/message_processors/verifier.rs, yarn.lock
- Change the upgrade gov wallet to multi-sig wallet.
- Added sub command to VIA cli called `multisig`, it allows the governance signers to build a transaction.
- Updated the indexer to index the upgrade execute inscription.
- Documented the VIA upgrade process.
This PR contains the implementation of the proposed [solution 1](https://www.notion.so/txfusion/Improved-Upgrade-Proposal-Mechanism-2088978a806480b99639ceb773cd1d53). It change the gov address to multisig.
=> Feat: Change the gov wallet to multisig

core/lib/config/src/configs/via_verifier.rs, docker/server/Dockerfile, docker/via-l1-indexer/Dockerfile, docker/via-verifier/Dockerfile
- Improve the container build by building only required binaries instead all of binaries.
=> build: build only required binaries in container for each via component

infrastructure/via/src/bootstrap.ts, infrastructure/via/src/transactions.ts
- Provide option to execute `via transaction` command directly on host  machine instead on running inside container.
- Fix the bug when updating the config file with bootstrap tx ids.
=> fix(via): provide option to generate transactions directly on host

docs/via_guides/upgrade.md, via_verifier/lib/via_musig2/Cargo.toml, via_verifier/lib/via_musig2/examples/transfer_utxos_from_bridge.rs
- Add script that allows the governance multisig to transfer UTXOs from the bridge address using the script path spending method.
- Document the transaction creating process with an example.  
- Follow the [docs](https://github.com/vianetwork/via-core/blob/feat/via-gov-script-transfer-utxo-from-bridge/docs/via_guides/upgrade.md#transfer-the-utxos-from-the-old-bridge-address-to-the-governance-wallet) how to transfer utxo from the bridge address to the governance wallet.
=> feat: add script to create a gov tx to transfer utxo from bridge

core/lib/types/src/via_bootstrap.rs
- Comment the gov wallet type validation for devnet because the current used one is P2WPKH.
=> fix: comment the gov wallet check

via_verifier/lib/verifier_dal/src/via_protocol_versions_dal.rs, via_verifier/node/via_zk_verifier/src/lib.rs
- Fix the zk verifier logic to update the database using an ACID transaction.
We encountered a bug on the devnet during the protocol upgrade from v26 to v27. The issue occurred because the upgrade transaction status was updated in the verifier database before completing zk verification. If an error occurred immediately after, the verifier would, in the next iteration, assume the batch was invalid since it could not find the upgrade transaction.
The fix improved the following:
- Moving the upgrade transaction status update after the zk verification is successfully completed.
- Performing the update within a database transaction (ACID) to ensure atomicity and prevent inconsistencies.
=> fix: mark the upgrade as processed using atomic tx
