vianetwork/via-core

- README.md
- docs/guides/via.md
> docs: add branches section

- core/bin/via_server/src/node_builder.rs
- Add btc_sender layers the `via_btc_inscription_aggregator` and the `via_btc_inscription_manager`.
> feat(via_server): add btc_sender layers

- core/node/via_btc_sender/src/aggregated_operations.rs
- core/node/via_btc_sender/src/btc_inscription_aggregator.rs
- core/node/via_btc_sender/src/btc_inscription_manager.rs
> Feat(btc sender) logs

- core/lib/via_btc_client/src/indexer/mod.rs
- core/lib/via_btc_client/src/indexer/parser.rs
- core/node/via_btc_watch/src/message_processors/l1_to_l2.rs
> feat: deposit flow

- infrastructure/via/src/database.ts
> fix: `database.ts` fixes

- core/lib/via_btc_client/src/indexer/mod.rs
> fix: via btc client tests

- core/bin/via_server/src/config.rs
- core/bin/via_server/src/main.rs
- core/bin/via_server/src/node_builder.rs
- core/lib/via_btc_client/src/indexer/mod.rs
- core/lib/via_btc_client/src/indexer/parser.rs
- core/lib/via_btc_client/src/types.rs
Address validation on indexer side
> fix: indexer validation, sender address

- Makefile
- core/lib/via_btc_client/examples/deposit.rs
- infrastructure/via/src/verifier.ts
- Add Makefile for easier Via local setup (run only one command `make via` for the basic setup workflow or `make all` for the full setup with Bitcoin explorer).
- Improve the deposit example for Devnet 1, by making network and rpc details configurable.
> Add Makefile and improve deposit example

- core/lib/via_btc_client/examples/bootstrap.rs
- docker-compose-via.yml
- infrastructure/via/src/bootstrap.ts
bootstrap command update 
regtest block generation improvement
> sync devnet 2 with main 

- infrastructure/via/src/database.ts
- Remove the prover migration when start the verifier db migration.
> fix: verifier dal migration

- docker/via-verifier/Dockerfile
Add dockerfile for via verifier.
> Docker setup for verifier

- Makefile
Add new commands to restart the Sequencer, the Coordinator, and the verifier with the correct ENVs.
1. Restart the Sequencer `make via-restart`
2. Restart the Coordinator `make via-restart-coordinator`
3. Restart the Verifier `make via-restart-verifier`
> feat: add restart cmds

- prover/crates/lib/prover_fri_types/src/lib.rs
> fix: protocol version

- docker/via-verifier/Dockerfile
Add verification keys to verifier docker image.
> Add verification keys to verifier image

- via_verifier/node/withdrawal_service/src/coordinator/api_impl.rs
- via_verifier/node/withdrawal_service/src/verifier/mod.rs
Improve the coordinator logging.
> feat: add logs to the coordinator

- via_verifier/lib/verifier_dal/src/via_votes_dal.rs
- via_verifier/node/withdrawal_service/src/coordinator/api_impl.rs
- via_verifier/node/withdrawal_service/src/verifier/mod.rs
> fix clippy warning

- core/node/via_btc_sender/src/btc_inscription_aggregator.rs
https://github.com/vianetwork/via-core/pull/116
> refactor: fetch the base system contracts from db

- .github/workflows/build-via-server.yml
- .github/workflows/tests-via.yml
- Add workflows for running tests and building via server.
> ci: add test and build workflows for via-server

- .github/workflows/build-via-verifier.yml
- Add workflow for building image for via verfier.
> ci: add the workflow for building via verifier image

- .gitmodules
- Change a branch for contracts submodule
> Set a default branch for contracts submodule

- core/node/via_block_reverter/src/tests.rs
- core/node/via_state_keeper/src/io/tests/tester.rs
- core/node/via_state_keeper/src/tests/mod.rs
- infrastructure/via/src/database.ts
- infrastructure/via/src/test/test.ts
- via_verifier/lib/verifier_dal/src/tests/mod.rs
> fix: via tests

- core/bin/via_server/src/node_builder.rs
- core/bin/zksync_server/src/node_builder.rs
- core/node/api_server/src/web3/state.rs
> fix: use option for via configs in the api

- Cargo.lock
- core/bin/external_node/Cargo.toml
- core/bin/external_node/src/config/mod.rs
- Fix external server orchestration layer
> fix: build

- Cargo.lock
- core/lib/via_btc_client/Cargo.toml
- core/lib/via_btc_client/src/client/mod.rs
- core/lib/via_btc_client/src/inscriber/mod.rs
- core/lib/via_btc_client/src/inscriber/script_builder.rs
- core/lib/via_btc_client/src/lib.rs
- core/lib/via_btc_client/src/metrics.rs
- core/lib/via_btc_client/src/utils.rs
- core/node/via_btc_sender/src/btc_inscription_manager.rs
- via_verifier/node/via_btc_sender/src/btc_inscription_manager.rs
- via_verifier/node/via_verifier_coordinator/src/coordinator/api_impl.rs
- via_verifier/node/via_verifier_coordinator/src/metrics.rs
- via_verifier/node/via_verifier_coordinator/src/verifier/mod.rs
- Add metrics to btc client.
- Improve logging .
- Fix btc sender track balance metric.
> feat: improve btc client logs and add metrics

- infrastructure/via/src/setup_en.ts
- infrastructure/via/src/verifier.ts
- Fix the cleaning the database for external node.
- Fix the setup by loading environment variables from file which has updated genesis transactions.
> fix(en): load enviroments from file during setup

- prover/crates/lib/prover_fri_types/src/lib.rs
> chore: update prover version

- .github/workflows/build-prover-components.yml
- Enable dynamic job spans for selected prover components.
> ci(prover): enable dynamic jobs spans for selected components

- docker/zk-environment/20.04_amd64_cuda_11_8.Dockerfile
- docker/zk-environment/20.04_amd64_cuda_12_0.Dockerfile
- docker/zk-environment/Dockerfile
- Bring back the `zk-environment` Dockerfiles in order to sync with ZKsync repository.
> chore: bring back the `zk-environment` Dockerfiles in order to sync ZKsync repo
